// src/sampleData.js

export const sampleData = [
  // Fruits
  { id: 1, name: "Apple", category: "Fruit" },
  { id: 2, name: "Apricot", category: "Fruit" },
  { id: 3, name: "Avocado", category: "Fruit" },
  { id: 4, name: "Banana", category: "Fruit" },
  { id: 5, name: "Blackberry", category: "Fruit" },
  { id: 6, name: "Blackcurrant", category: "Fruit" },
  { id: 7, name: "Blueberry", category: "Fruit" },
  { id: 8, name: "Boysenberry", category: "Fruit" },
  { id: 9, name: "Cherry", category: "Fruit" },
  { id: 10, name: "Coconut", category: "Fruit" },
  { id: 11, name: "Cranberry", category: "Fruit" },
  { id: 12, name: "Date", category: "Fruit" },
  { id: 13, name: "Dragonfruit", category: "Fruit" },
  { id: 14, name: "Durian", category: "Fruit" },
  { id: 15, name: "Elderberry", category: "Fruit" },
  { id: 16, name: "Feijoa", category: "Fruit" },
  { id: 17, name: "Fig", category: "Fruit" },
  { id: 18, name: "Grape", category: "Fruit" },
  { id: 19, name: "Grapefruit", category: "Fruit" },
  { id: 20, name: "Guava", category: "Fruit" },
  { id: 21, name: "Huckleberry", category: "Fruit" },
  { id: 22, name: "Jackfruit", category: "Fruit" },
  { id: 23, name: "Jujube", category: "Fruit" },
  { id: 24, name: "Kiwi", category: "Fruit" },
  { id: 25, name: "Kumquat", category: "Fruit" },
  { id: 26, name: "Lemon", category: "Fruit" },
  { id: 27, name: "Lime", category: "Fruit" },
  { id: 28, name: "Lychee", category: "Fruit" },
  { id: 29, name: "Mango", category: "Fruit" },
  { id: 30, name: "Marionberry", category: "Fruit" },
  { id: 31, name: "Melon", category: "Fruit" },
  { id: 32, name: "Nectarine", category: "Fruit" },
  { id: 33, name: "Orange", category: "Fruit" },
  { id: 34, name: "Papaya", category: "Fruit" },
  { id: 35, name: "Passionfruit", category: "Fruit" },
  { id: 36, name: "Peach", category: "Fruit" },
  { id: 37, name: "Pear", category: "Fruit" },
  { id: 38, name: "Persimmon", category: "Fruit" },
  { id: 39, name: "Pineapple", category: "Fruit" },
  { id: 40, name: "Plum", category: "Fruit" },
  { id: 41, name: "Pomegranate", category: "Fruit" },
  { id: 42, name: "Quince", category: "Fruit" },
  { id: 43, name: "Raspberry", category: "Fruit" },
  { id: 44, name: "Strawberry", category: "Fruit" },
  { id: 45, name: "Tangerine", category: "Fruit" },
  { id: 46, name: "Watermelon", category: "Fruit" },

  // Vegetables
  { id: 47, name: "Artichoke", category: "Vegetable" },
  { id: 48, name: "Asparagus", category: "Vegetable" },
  { id: 49, name: "Beetroot", category: "Vegetable" },
  { id: 50, name: "Bell pepper", category: "Vegetable" },
  { id: 51, name: "Broccoli", category: "Vegetable" },
  { id: 52, name: "Brussels sprout", category: "Vegetable" },
  { id: 53, name: "Cabbage", category: "Vegetable" },
  { id: 54, name: "Carrot", category: "Vegetable" },
  { id: 55, name: "Cauliflower", category: "Vegetable" },
  { id: 56, name: "Celery", category: "Vegetable" },
  { id: 57, name: "Corn", category: "Vegetable" },
  { id: 58, name: "Cucumber", category: "Vegetable" },
  { id: 59, name: "Eggplant", category: "Vegetable" },
  { id: 60, name: "Garlic", category: "Vegetable" },
  { id: 61, name: "Ginger", category: "Vegetable" },
  { id: 62, name: "Kale", category: "Vegetable" },
  { id: 63, name: "Leek", category: "Vegetable" },
  { id: 64, name: "Lettuce", category: "Vegetable" },
  { id: 65, name: "Mushroom", category: "Vegetable" },
  { id: 66, name: "Onion", category: "Vegetable" },
  { id: 67, name: "Parsnip", category: "Vegetable" },
  { id: 68, name: "Pea", category: "Vegetable" },
  { id: 69, name: "Potato", category: "Vegetable" },
  { id: 70, name: "Pumpkin", category: "Vegetable" },
  { id: 71, name: "Radish", category: "Vegetable" },
  { id: 72, name: "Spinach", category: "Vegetable" },
  { id: 73, name: "Sweet potato", category: "Vegetable" },
  { id: 74, name: "Tomato", category: "Vegetable" },
  { id: 75, name: "Turnip", category: "Vegetable" },
  { id: 76, name: "Zucchini", category: "Vegetable" },

  // --- NEW Programming & Database Terms ---
  { id: 101, name: "ACID", category: "Database" },
  { id: 102, name: "Algorithm", category: "Programming" },
  { id: 103, name: "API", category: "Programming" },
  { id: 104, name: "Application", category: "Programming" },
  { id: 105, name: "Array", category: "Data Structure" },
  { id: 106, name: "Authentication", category: "Security" },
  { id: 107, name: "Authorization", category: "Security" },
  { id: 108, name: "Backend", category: "Programming" },
  { id: 109, name: "Binary Search", category: "Algorithm" },
  { id: 110, name: "Binary Tree", category: "Data Structure" },
  { id: 111, name: "Blockchain", category: "Technology" },
  { id: 112, name: "Cache", category: "System Design" },
  { id: 113, name: "CAP Theorem", category: "Database" },
  { id: 114, name: "Class", category: "Programming" },
  { id: 115, name: "Client", category: "System Design" },
  { id: 116, name: "Cloud Computing", category: "Technology" },
  { id: 117, name: "Compiler", category: "Programming" },
  { id: 118, name: "Component", category: "Programming" },
  { id: 119, name: "Concurrency", category: "System Design" },
  { id: 120, name: "Container", category: "Technology" },
  { id: 121, name: "Database", category: "Database" },
  { id: 122, name: "Data Structure", category: "Programming" },
  { id: 123, name: "Data Visualization", category: "Technology" },
  { id: 124, name: "Debugging", category: "Programming" },
  { id: 125, name: "Deployment", category: "DevOps" },
  { id: 126, name: "Docker", category: "Technology" },
  { id: 127, name: "DOM", category: "Web Dev" },
  { id: 128, name: "Encryption", category: "Security" },
  { id: 129, name: "Endpoint", category: "API" },
  { id: 130, name: "Framework", category: "Programming" },
  { id: 131, name: "Frontend", category: "Programming" },
  { id: 132, name: "Function", category: "Programming" },
  { id: 133, name: "Git", category: "DevOps" },
  { id: 134, name: "GraphQL", category: "API" },
  { id: 135, name: "Hash Table", category: "Data Structure" },
  { id: 136, name: "HTTP", category: "Web Dev" },
  { id: 137, name: "Index", category: "Database" },
  { id: 138, name: "Inheritance", category: "Programming" },
  { id: 139, name: "Integration", category: "DevOps" },
  { id: 140, name: "Interpreter", category: "Programming" },
  { id: 141, name: "JavaScript", category: "Language" },
  { id: 142, name: "JSON", category: "Data Format" },
  { id: 143, name: "JWT", category: "Security" },
  { id: 144, name: "Kubernetes", category: "Technology" },
  { id: 145, name: "Latency", category: "System Design" },
  { id: 146, name: "Library", category: "Programming" },
  { id: 147, name: "Linked List", category: "Data Structure" },
  { id: 148, name: "Load Balancer", category: "System Design" },
  { id: 149, name: "Machine Learning", category: "Technology" },
  { id: 150, name: "Microservices", category: "System Design" },
  { id: 151, name: "MongoDB", category: "NoSQL" },
  { id: 152, name: "MySQL", category: "SQL" },
  { id: 153, name: "Network", category: "System Design" },
  { id: 154, name: "Node.js", category: "Framework" },
  { id: 155, name: "NoSQL", category: "Database" },
  { id: 156, name: "Object", category: "Programming" },
  { id: 157, name: "OAuth", category: "Security" },
  { id: 158, name: "ORM", category: "Database" },
  { id: 159, name: "Packet", category: "Network" },
  { id: 160, name: "Polymorphism", category: "Programming" },
  { id: 161, name: "PostgreSQL", category: "SQL" },
  { id: 162, name: "Promise", category: "JavaScript" },
  { id: 163, name: "Protocol", category: "Network" },
  { id: 164, name: "Python", category: "Language" },
  { id: 165, name: "Queue", category: "Data Structure" },
  { id: 166, name: "React", category: "Framework" },
  { id: 167, name: "Recursion", category: "Algorithm" },
  { id: 168, name: "Redis", category: "NoSQL" },
  { id: 169, name: "Replication", category: "Database" },
  { id: 170, name: "Request", category: "Web Dev" },
  { id: 171, name: "Response", category: "Web Dev" },
  { id: 172, name: "REST", category: "API" },
  { id: 173, name: "Router", category: "Network" },
  { id: 174, name: "Scalability", category: "System Design" },
  { id: 175, name: "Schema", category: "Database" },
  { id: 176, name: "Server", category: "System Design" },
  { id: 177, name: "Sharding", category: "Database" },
  { id: 178, name: "Socket", category: "Network" },
  { id: 179, name: "SQL", category: "Database" },
  { id: 180, name: "Stack", category: "Data Structure" },
  { id: 181, name: "State", category: "Programming" },
  { id: 182, name: "System Design", category: "Programming" },
  { id: 183, name: "TCP", category: "Network" },
  { id: 184, name: "Testing", category: "Programming" },
  { id: 185, name: "Thread", category: "System Design" },
  { id: 186, name: "Token", category: "Security" },
  { id: 187, name: "Transaction", category: "Database" },
  { id: 188, name: "Trie", category: "Data Structure" },
  { id: 189, name: "TypeScript", category: "Language" },
  { id: 190, name: "UDP", category: "Network" },
  { id: 191, name: "UI", category: "Programming" },
  { id: 192, name: "Unit Test", category: "Testing" },
  { id: 193, name: "UX", category: "Design" },
  { id: 194, name: "Variable", category: "Programming" },
  { id: 195, name: "Virtual DOM", category: "Web Dev" },
  { id: 196, name: "Vue", category: "Framework" },
  { id: 197, name: "Webpack", category: "Tool" },
  { id: 198, name: "Websocket", category: "Web Dev" },
  { id: 199, name: "XML", category: "Data Format" },
];
