// src/sampleData.js

// src/sampleData.js

export const sampleData = [
  // ~1000 Most Common English Words
  { id: 1, name: 'the', category: 'Common Word' },
  { id: 2, name: 'be', category: 'Common Word' },
  { id: 3, name: 'to', category: 'Common Word' },
  { id: 4, name: 'of', category: 'Common Word' },
  { id: 5, name: 'and', category: 'Common Word' },
  { id: 6, name: 'a', category: 'Common Word' },
  { id: 7, name: 'in', category: 'Common Word' },
  { id: 8, name: 'that', category: 'Common Word' },
  { id: 9, name: 'have', category: 'Common Word' },
  { id: 10, name: 'I', category: 'Common Word' },
  { id: 11, name: 'it', category: 'Common Word' },
  { id: 12, name: 'for', category: 'Common Word' },
  { id: 13, name: 'not', category: 'Common Word' },
  { id: 14, name: 'on', category: 'Common Word' },
  { id: 15, name: 'with', category: 'Common Word' },
  { id: 16, name: 'he', category: 'Common Word' },
  { id: 17, name: 'as', category: 'Common Word' },
  { id: 18, name: 'you', category: 'Common Word' },
  { id: 19, name: 'do', category: 'Common Word' },
  { id: 20, name: 'at', category: 'Common Word' },
  { id: 21, name: 'this', category: 'Common Word' },
  { id: 22, name: 'but', category: 'Common Word' },
  { id: 23, name: 'his', category: 'Common Word' },
  { id: 24, name: 'by', category: 'Common Word' },
  { id: 25, name: 'from', category: 'Common Word' },
  { id: 26, name: 'they', category: 'Common Word' },
  { id: 27, name: 'we', category: 'Common Word' },
  { id: 28, name: 'say', category: 'Common Word' },
  { id: 29, name: 'her', category: 'Common Word' },
  { id: 30, name: 'she', category: 'Common Word' },
  { id: 31, name: 'or', category: 'Common Word' },
  { id: 32, name: 'an', category: 'Common Word' },
  { id: 33, name: 'will', category: 'Common Word' },
  { id: 34, name: 'my', category: 'Common Word' },
  { id: 35, name: 'one', category: 'Common Word' },
  { id: 36, name: 'all', category: 'Common Word' },
  { id: 37, name: 'would', category: 'Common Word' },
  { id: 38, name: 'there', category: 'Common Word' },
  { id: 39, name: 'their', category: 'Common Word' },
  { id: 40, name: 'what', category: 'Common Word' },
  { id: 41, name: 'so', category: 'Common Word' },
  { id: 42, name: 'up', category: 'Common Word' },
  { id: 43, name: 'out', category: 'Common Word' },
  { id: 44, name: 'if', category: 'Common Word' },
  { id: 45, name: 'about', category: 'Common Word' },
  { id: 46, name: 'who', category: 'Common Word' },
  { id: 47, name: 'get', category: 'Common Word' },
  { id: 48, name: 'which', category: 'Common Word' },
  { id: 49, name: 'go', category: 'Common Word' },
  { id: 50, name: 'me', category: 'Common Word' },
  { id: 51, name: 'when', category: 'Common Word' },
  { id: 52, name: 'make', category: 'Common Word' },
  { id: 53, name: 'can', category: 'Common Word' },
  { id: 54, name: 'like', category: 'Common Word' },
  { id: 55, name: 'time', category: 'Common Word' },
  { id: 56, name: 'no', category: 'Common Word' },
  { id: 57, name: 'just', category: 'Common Word' },
  { id: 58, name: 'him', category: 'Common Word' },
  { id: 59, name: 'know', category: 'Common Word' },
  { id: 60, name: 'take', category: 'Common Word' },
  { id: 61, name: 'people', category: 'Common Word' },
  { id: 62, name: 'into', category: 'Common Word' },
  { id: 63, name: 'year', category: 'Common Word' },
  { id: 64, name: 'your', category: 'Common Word' },
  { id: 65, name: 'good', category: 'Common Word' },
  { id: 66, name: 'some', category: 'Common Word' },
  { id: 67, name: 'could', category: 'Common Word' },
  { id: 68, name: 'them', category: 'Common Word' },
  { id: 69, name: 'see', category: 'Common Word' },
  { id: 70, name: 'other', category: 'Common Word' },
  { id: 71, name: 'than', category: 'Common Word' },
  { id: 72, name: 'then', category: 'Common Word' },
  { id: 73, name: 'now', category: 'Common Word' },
  { id: 74, name: 'look', category: 'Common Word' },
  { id: 75, name: 'only', category: 'Common Word' },
  { id: 76, name: 'come', category: 'Common Word' },
  { id: 77, name: 'its', category: 'Common Word' },
  { id: 78, name: 'over', category: 'Common Word' },
  { id: 79, name: 'think', category: 'Common Word' },
  { id: 80, name: 'also', category: 'Common Word' },
  { id: 81, name: 'back', category: 'Common Word' },
  { id: 82, name: 'after', category: 'Common Word' },
  { id: 83, name: 'use', category: 'Common Word' },
  { id: 84, name: 'two', category: 'Common Word' },
  { id: 85, name: 'how', category: 'Common Word' },
  { id: 86, name: 'our', category: 'Common Word' },
  { id: 87, name: 'work', category: 'Common Word' },
  { id: 88, name: 'first', category: 'Common Word' },
  { id: 89, name: 'well', category: 'Common Word' },
  { id: 90, name: 'way', category: 'Common Word' },
  { id: 91, name: 'even', category: 'Common Word' },
  { id: 92, name: 'new', category: 'Common Word' },
  { id: 93, name: 'want', category: 'Common Word' },
  { id: 94, name: 'because', category: 'Common Word' },
  { id: 95, name: 'any', category: 'Common Word' },
  { id: 96, name: 'these', category: 'Common Word' },
  { id: 97, name: 'give', category: 'Common Word' },
  { id: 98, name: 'day', category: 'Common Word' },
  { id: 99, name: 'most', category: 'Common Word' },
  { id: 100, name: 'us', category: 'Common Word' },
  // ... (continuing the common words)
  { id: 101, name: 'find', category: 'Common Word' },
  { id: 102, name: 'here', category: 'Common Word' },
  { id: 103, name: 'thing', category: 'Common Word' },
  { id: 104, name: 'give', category: 'Common Word' },
  { id: 105, name: 'many', category: 'Common Word' },
  { id: 106, name: 'well', category: 'Common Word' },
  { id: 107, name: 'only', category: 'Common Word' },
  { id: 108, name: 'those', category: 'Common Word' },
  { id: 109, name: 'tell', category: 'Common Word' },
  { id: 110, name: 'one', category: 'Common Word' },
  { id: 111, name: 'very', category: 'Common Word' },
  { id: 112, name: 'her', category: 'Common Word' },
  { id: 113, name: 'even', category: 'Common Word' },
  { id: 114, name: 'back', category: 'Common Word' },
  { id: 115, name: 'any', category: 'Common Word' },
  { id: 116, name: 'good', category: 'Common Word' },
  { id: 117, name: 'woman', category: 'Common Word' },
  { id: 118, name: 'through', category: 'Common Word' },
  { id: 119, name: 'us', category: 'Common Word' },
  { id: 120, name: 'life', category: 'Common Word' },
  { id: 121, name: 'child', category: 'Common Word' },
  { id: 123, name: 'work', category: 'Common Word' },
  { id: 124, name: 'down', category: 'Common Word' },
  { id: 125, name: 'may', category: 'Common Word' },
  { id: 126, name: 'after', category: 'Common Word' },
  { id: 127, name: 'should', category: 'Common Word' },
  { id: 128, name: 'call', category: 'Common Word' },
  { id: 129, name: 'world', category: 'Common Word' },
  { id: 130, name: 'over', category: 'Common Word' },
  { id: 131, name: 'school', category: 'Common Word' },
  { id: 132, name: 'still', category: 'Common Word' },
  { id: 133, name: 'try', category: 'Common Word' },
  { id: 134, name: 'in', category: 'Common Word' },
  { id: 135, name: 'as', category: 'Common Word' },
  { id: 136, name: 'last', category: 'Common Word' },
  { id: 137, name: 'ask', category: 'Common Word' },
  { id: 138, name: 'need', category: 'Common Word' },
  { id: 139, name: 'too', category: 'Common Word' },
  { id: 140, name: 'feel', category: 'Common Word' },
  { id: 141, name: 'three', category: 'Common Word' },
  { id: 142, name: 'when', category: 'Common Word' },
  { id: 143, name: 'low', category: 'Common Word' },
  { id: 144, name: 'state', category: 'Common Word' },
  { id: 145, name: 'never', category: 'Common Word' },
  { id: 146, name: 'become', category: 'Common Word' },
  { id: 147, name: 'between', category: 'Common Word' },
  { id: 148, name: 'high', category: 'Common Word' },
  { id: 149, name: 'really', category: 'Common Word' },
  { id: 150, name: 'something', category: 'Common Word' },
  { id: 151, name: 'most', category: 'Common Word' },
  { id: 152, name: 'another', category: 'Common Word' },
  { id: 153, name: 'much', category: 'Common Word' },
  { id: 154, name: 'family', category: 'Common Word' },
  { id: 155, name: 'own', category: 'Common Word' },
  { id: 156, name: 'out', category: 'Common Word' },
  { id: 157, name: 'leave', category: 'Common Word' },
  { id: 158, name: 'put', category: 'Common Word' },
  { id: 159, name: 'old', category: 'Common Word' },
  { id: 160, name: 'while', category: 'Common Word' },
  { id: 161, name: 'mean', category: 'Common Word' },
  { id: 162, name: 'on', category: 'Common Word' },
  { id: 163, name: 'keep', category: 'Common Word' },
  { id: 164, name: 'student', category: 'Common Word' },
  { id: 165, name: 'why', category: 'Common Word' },
  { id: 166, name: 'let', category: 'Common Word' },
  { id: 167, name: 'great', category: 'Common Word' },
  { id: 168, name: 'same', category: 'Common Word' },
  { id: 169, name: 'big', category: 'Common Word' },
  { id: 170, name: 'group', category: 'Common Word' },
  { id: 171, name: 'begin', category: 'Common Word' },
  { id: 172, name: 'seem', category: 'Common Word' },
  { id: 173, name: 'country', category: 'Common Word' },
  { id: 174, name: 'help', category: 'Common Word' },
  { id: 175, name: 'talk', category: 'Common Word' },
  { id: 176, name: 'where', category: 'Common Word' },
  { id: 177, name: 'turn', category: 'Common Word' },
  { id: 178, name: 'problem', category: 'Common Word' },
  { id: 179, name: 'every', category: 'Common Word' },
  { id: 180, name: 'start', category: 'Common Word' },
  { id: 181, name: 'hand', category: 'Common Word' },
  { id: 182, name: 'might', category: 'Common Word' },
  { id: 183, name: 'American', category: 'Common Word' },
  { id: 184, name: 'show', category: 'Common Word' },
  { id: 185, name: 'part', category: 'Common Word' },
  { id: 186, name: 'about', category: 'Common Word' },
  { id: 187, name: 'against', category: 'Common Word' },
  { id: 188, name: 'place', category: 'Common Word' },
  { id: 189, name: 'over', category: 'Common Word' },
  { id: 190, name: 'such', category: 'Common Word' },
  { id: 191, name: 'again', category: 'Common Word' },
  { id: 192, name: 'few', category: 'Common Word' },
  { id: 193, name: 'case', category: 'Common Word' },
  { id: 194, name: 'most', category: 'Common Word' },
  { id: 195, name: 'week', category: 'Common Word' },
  { id: 196, name: 'company', category: 'Common Word' },
  { id: 197, name: 'where', category: 'Common Word' },
  { id: 198, name: 'system', category: 'Common Word' },
  { id: 199, name: 'each', category: 'Common Word' },
  { id: 200, name: 'right', category: 'Common Word' },
  // ... and hundreds more common words
  { id: 998, name: 'yellow', category: 'Common Word' },
  { id: 999, name: 'gun', category: 'Common Word' },
  { id: 1000, name: 'allow', category: 'Common Word' },

  // --- Technology, Programming, Database, Data Structure, System Design ---
  { id: 1001, name: 'ACID', category: 'Database' },
  { id: 1002, name: 'Algorithm', category: 'Programming' },
  { id: 1003, name: 'API', category: 'Programming' },
  { id: 1004, name: 'Application', category: 'Programming' },
  { id: 1005, name: 'Array', category: 'Data Structure' },
  { id: 1006, name: 'Authentication', category: 'Security' },
  { id: 1007, name: 'Authorization', category: 'Security' },
  { id: 1008, name: 'Backend', category: 'Programming' },
  { id: 1009, name: 'Binary Search', category: 'Algorithm' },
  { id: 1010, name: 'Binary Tree', category: 'Data Structure' },
  { id: 1011, name: 'Blockchain', category: 'Technology' },
  { id: 1012, name: 'Cache', category: 'System Design' },
  { id: 1013, name: 'CAP Theorem', category: 'Database' },
  { id: 1014, name: 'Class', category: 'Programming' },
  { id: 1015, name: 'Client', category: 'System Design' },
  { id: 1016, name: 'Cloud Computing', category: 'Technology' },
  { id: 1017, name: 'Compiler', category: 'Programming' },
  { id: 1018, name: 'Component', category: 'Programming' },
  { id: 1019, name: 'Concurrency', category: 'System Design' },
  { id: 1020, name: 'Container', category: 'Technology' },
  { id: 1021, name: 'Database', category: 'Database' },
  { id: 1022, name: 'Data Structure', category: 'Programming' },
  { id: 1023, name: 'Data Visualization', category: 'Technology' },
  { id: 1024, name: 'Debugging', category: 'Programming' },
  { id: 1025, name: 'Deployment', category: 'DevOps' },
  { id: 1026, name: 'Docker', category: 'Technology' },
  { id: 1027, name: 'DOM', category: 'Web Dev' },
  { id: 1028, name: 'Encryption', category: 'Security' },
  { id: 1029, name: 'Endpoint', category: 'API' },
  { id: 1030, name: 'Framework', category: 'Programming' },
  { id: 1031, name: 'Frontend', category: 'Programming' },
  { id: 1032, name: 'Function', category: 'Programming' },
  { id: 1033, name: 'Git', category: 'DevOps' },
  { id: 1034, name: 'GraphQL', category: 'API' },
  { id: 1035, name: 'Hash Table', category: 'Data Structure' },
  { id: 1036, name: 'HTTP', category: 'Web Dev' },
  { id: 1037, name: 'Index', category: 'Database' },
  { id: 1038, name: 'Inheritance', category: 'Programming' },
  { id: 1039, name: 'Integration', category: 'DevOps' },
  { id: 1040, name: 'Interpreter', category: 'Programming' },
  { id: 1041, name: 'JavaScript', category: 'Language' },
  { id: 1042, name: 'JSON', category: 'Data Format' },
  { id: 1043, name: 'JWT', category: 'Security' },
  { id: 1044, name: 'Kubernetes', category: 'Technology' },
  { id: 1045, name: 'Latency', category: 'System Design' },
  { id: 1046, name: 'Library', category: 'Programming' },
  { id: 1047, name: 'Linked List', category: 'Data Structure' },
  { id: 1048, name: 'Load Balancer', category: 'System Design' },
  { id: 1049, name: 'Machine Learning', category: 'Technology' },
  { id: 1050, name: 'Microservices', category: 'System Design' },
  { id: 1051, name: 'MongoDB', category: 'NoSQL' },
  { id: 1052, name: 'MySQL', category: 'SQL' },
  { id: 1053, name: 'Network', category: 'System Design' },
  { id: 1054, name: 'Node.js', category: 'Framework' },
  { id: 1055, name: 'NoSQL', category: 'Database' },
  { id: 1056, name: 'Object', category: 'Programming' },
  { id: 1057, name: 'OAuth', category: 'Security' },
  { id: 1058, name: 'ORM', category: 'Database' },
  { id: 1059, name: 'Packet', category: 'Network' },
  { id: 1060, name: 'Polymorphism', category: 'Programming' },
  { id: 1061, name: 'PostgreSQL', category: 'SQL' },
  { id: 1062, name: 'Promise', category: 'JavaScript' },
  { id: 1063, name: 'Protocol', category: 'Network' },
  { id: 1064, name: 'Python', category: 'Language' },
  { id: 1065, name: 'Queue', category: 'Data Structure' },
  { id: 1066, name: 'React', category: 'Framework' },
  { id: 1067, name: 'Recursion', category: 'Algorithm' },
  { id: 1068, name: 'Redis', category: 'NoSQL' },
  { id: 1069, name: 'Replication', category: 'Database' },
  { id: 1070, name: 'Request', category: 'Web Dev' },
  { id: 1071, name: 'Response', category: 'Web Dev' },
  { id: 1072, name: 'REST', category: 'API' },
  { id: 1073, name: 'Router', category: 'Network' },
  { id: 1074, name: 'Scalability', category: 'System Design' },
  { id: 1075, name: 'Schema', category: 'Database' },
  { id: 1076, name: 'Server', category: 'System Design' },
  { id: 1077, name: 'Sharding', category: 'Database' },
  { id: 1078, name: 'Socket', category: 'Network' },
  { id: 1079, name: 'SQL', category: 'Database' },
  { id: 1080, name: 'Stack', category: 'Data Structure' },
  { id: 1081, name: 'State', category: 'Programming' },
  { id: 1082, name: 'System Design', category: 'Programming' },
  { id: 1083, name: 'TCP', category: 'Network' },
  { id: 1084, name: 'Testing', category: 'Programming' },
  { id: 1085, name: 'Thread', category: 'System Design' },
  { id: 1086, name: 'Token', category: 'Security' },
  { id: 1087, name: 'Transaction', category: 'Database' },
  { id: 1088, name: 'Trie', category: 'Data Structure' },
  { id: 1089, name: 'TypeScript', category: 'Language' },
  { id: 1090, name: 'UDP', category: 'Network' },
  { id: 1091, name: 'UI', category: 'Programming' },
  { id: 1092, name: 'Unit Test', category: 'Testing' },
  { id: 1093, name: 'UX', category: 'Design' },
  { id: 1094, name: 'Variable', category: 'Programming' },
  { id: 1095, name: 'Virtual DOM', category: 'Web Dev' },
  { id: 1096, name: 'Vue', category: 'Framework' },
  { id: 1097, name: 'Webpack', category: 'Tool' },
  { id: 1098, name: 'Websocket', category: 'Web Dev' },
  { id: 1099, name: 'XML', category: 'Data Format' },
  
  // Additional Categories for Variety
  { id: 1100, name: 'Photosynthesis', category: 'Science' },
  { id: 1101, name: 'Gravity', category: 'Science' },
  { id: 1102, name: 'Evolution', category: 'Science' },
  { id: 1103, name: 'Galaxy', category: 'Science' },
  { id: 1104, name: 'Molecule', category: 'Science' },
  { id: 1105, 'name': 'Geology', 'category': 'Science' },
  { id: 1106, 'name': 'Amazon River', 'category': 'Geography' },
  { id: 1107, 'name': 'Mount Everest', 'category': 'Geography' },
  { id: 1108, 'name': 'Sahara Desert', 'category': 'Geography' },
  { id: 1109, 'name': 'Nile River', 'category': 'Geography' },
  { id: 1110, 'name': 'Pacific Ocean', 'category': 'Geography' },
  { id: 1111, 'name': 'Renaissance', 'category': 'History' },
  { id: 1112, 'name': 'Industrial Revolution', 'category': 'History' },
  { id: 1113, 'name': 'World War I', 'category': 'History' },
  { id: 1114, 'name': 'World War II', 'category': 'History' },
  { id: 1115, 'name': 'Cold War', 'category': 'History' }
];
